// JSON WEB TOKEN


// HMAC:
// RSA: CHAVE PÚBLICA/PRIVADA:

// 3 PARTES;
// HEADER (INFORMAÇÕES DO TOKEN): { "alg": "HS256", "typ": "JWT" }
// PAYLOAD (INFORMAÇÕES DO USUÁRIO + PERMISSÕES):
// SIGNATURE (ASSINATURA = HEADER + PAYLOAD):