# HABILITAR HYPER-V

# INSTALAÇÃO DO WSL
wsl --install

# REINICIAR O COMPUTADOR

# CRIAR USUÁRIO E SENHA

# INSTALAR DOCKER DESKTOP
  # INSTALL REQUIRED WINDOWS COMPONENTS FOR WSL2
  # ADD SHORTCUT TO DESKTOP